/*******************************************************************************
 * @brief Event Driven Framework (EDF) fuzzing integration.
 *
 * @copyright
 * Copyright (c) 2026 FBS93.
 * See the LICENSE file of this project for license details.
 * This notice shall be retained in all copies or substantial portions
 * of the software.
 *
 * @warning
 * This software is provided "as is", without any express or implied warranty.
 * The user assumes all responsibility for its use and any consequences.
 ******************************************************************************/

#ifndef EDF_FUZZ_H
#define EDF_FUZZ_H

/*******************************************************************************
 * INCLUDES
 ******************************************************************************/

/* -----------------------------------------------------------------------------
 * System library headers
 * -------------------------------------------------------------------------- */
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* -----------------------------------------------------------------------------
 * External library headers
 * -------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
 * Project-specific headers
 * -------------------------------------------------------------------------- */
#include "ebf_config.h"
#include "edf_event.h"

#if (EBF_PORT == EBF_PORT_POSIX_NON_PREEMPTIVE_FUZZ)

/*******************************************************************************
 * PUBLIC MACROS
 ******************************************************************************/

/**
 * @brief Define the single global fuzzable-event table.
 */
#define EDF_FUZZ_EVENT_TABLE(...)                                         \
  const EDF_fuzz_eventDescriptor_t EDF_fuzz_eventTable[] = {__VA_ARGS__}; \
  const size_t EDF_fuzz_eventTableLen =                                   \
    sizeof(EDF_fuzz_eventTable) / sizeof(EDF_fuzz_eventTable[0U])

/**
 * @brief Add an immutable fuzzable event.
 *
 * @param[in] sig Event signal associated with the immutable event.
 * @param[in] event_ptr Pointer to the immutable event instance.
 */
#define EDF_FUZZ_IMMUTABLE_EVENT(sig, event_ptr) \
  {(EDF_event_signal_t)(sig), false, (event_ptr), 0U}

/**
 * @brief Add a mutable fuzzable event.
 *
 * @param[in] sig Event signal associated with the mutable event.
 * @param[in] event_size Full mutable event size, including EDF_event_t.
 */
#define EDF_FUZZ_MUTABLE_EVENT(sig, event_size) \
  {(EDF_event_signal_t)(sig), true, NULL, (uint_fast16_t)(event_size)}

/*******************************************************************************
 * PUBLIC TYPEDEFS
 ******************************************************************************/

/**
 * @brief Fuzzable event descriptor.
 *
 * @note This structure is part of the fuzz-port integration contract and is
 * consumed internally by EDF. Applications shall define descriptors only
 * through the table macros provided by this header.
 */
typedef struct
{
  EDF_event_signal_t sig;             /**< Event signal published by EDF. */
  bool is_mutable;                    /**< Mutable event descriptor flag. */
  const EDF_event_t* immutable_event; /**< Immutable event instance. */
  uint_fast16_t mutable_event_size;   /**< Mutable event size in bytes. */
} EDF_fuzz_eventDescriptor_t;

/*******************************************************************************
 * PUBLIC VARIABLES
 ******************************************************************************/

/**
 * @brief Single global fuzzable-event table generated by the application.
 *
 * @note This symbol is intended for EDF internal use. Applications shall define
 * it with @ref EDF_FUZZ_EVENT_TABLE and shall not access it directly.
 */
extern const EDF_fuzz_eventDescriptor_t EDF_fuzz_eventTable[];

/**
 * @brief Number of entries in the single global fuzzable-event table.
 *
 * @note This symbol is intended for EDF internal use. Applications shall define
 * it with @ref EDF_FUZZ_EVENT_TABLE and shall not access it directly.
 */
extern const size_t EDF_fuzz_eventTableLen;

/*******************************************************************************
 * PUBLIC FUNCTIONS
 ******************************************************************************/

#else

#error "edf_fuzz.h is only available with EBF_PORT_POSIX_NON_PREEMPTIVE_FUZZ"

#endif  // (EBF_PORT == EBF_PORT_POSIX_NON_PREEMPTIVE_FUZZ)

#endif /* EDF_FUZZ_H */
